#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := modbus_slave

EXTRA_COMPONENT_DIRS := $(IDF_PATH)/examples\protocols\modbus\serial\modbus_simple_slave\components
include $(IDF_PATH)/make/project.mk

